package org.testin.sftp;

import org.apache.sshd.common.config.keys.AuthorizedKeyEntry;
import org.apache.sshd.common.config.keys.KeyUtils;
import org.apache.sshd.common.config.keys.PublicKeyEntry;
import org.apache.sshd.common.file.virtualfs.VirtualFileSystemFactory;
import org.apache.sshd.server.SshServer;
import org.apache.sshd.server.keyprovider.SimpleGeneratorHostKeyProvider;
import org.apache.sshd.sftp.server.SftpSubsystemFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.security.KeyPair;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;

/**
 * A real SFTP server, inside the test JVM, on a port nobody chose.
 * <p>
 * So the transport is exercised against an actual SSH conversation on every
 * build - key exchange, authentication, the SFTP subsystem - rather than against
 * a mock that agrees with whatever the code does. It needs no machine set up, no
 * administrator, and no open port, which is what makes it something CI and a
 * second laptop can both run.
 * <p>
 * Test scope only. This never reaches the distribution, which is also why the
 * library behind it is acceptable here and was not acceptable as the client: its
 * accept-any-host-key default is a property of its <em>client</em> builder, and
 * nothing here is a client.
 */
final class SftpTestServer implements AutoCloseable {

    static final String USER = "tester";
    static final String PASSWORD = "not-a-real-secret";

    private final SshServer server;
    private final Path directory;
    private final Path root;

    private SftpTestServer(final SshServer server, final Path directory, final Path root) {
        this.server = server;
        this.directory = directory;
        this.root = root;
    }

    static SftpTestServer start() throws IOException {
        final Path directory = Files.createTempDirectory("testin-sftp");
        final Path root = Files.createDirectories(directory.resolve("srv"));

        final SshServer server = SshServer.setUpDefaultServer();
        server.setPort(0);
        server.setKeyPairProvider(new SimpleGeneratorHostKeyProvider(directory.resolve("host.ser")));
        server.setPasswordAuthenticator((user, password, session) ->
                USER.equals(user) && PASSWORD.equals(password));
        server.setSubsystemFactories(List.of(new SftpSubsystemFactory()));
        server.setFileSystemFactory(new VirtualFileSystemFactory(root));
        server.start();

        return new SftpTestServer(server, directory, root);
    }

    int port() {
        return server.getPort();
    }

    /**
     * Makes the server accept one public key, and nothing else.
     * <p>
     * Named rather than "accept any", so a test that authenticates with the
     * wrong key is refused by the server for the reason a real one would refuse
     * it.
     */
    void acceptOnly(final Path publicKeyFile) throws IOException, GeneralSecurityException {
        final AuthorizedKeyEntry entry = AuthorizedKeyEntry.readAuthorizedKeys(publicKeyFile).iterator().next();
        final java.security.PublicKey allowed = entry.resolvePublicKey(null, null, null);

        server.setPublickeyAuthenticator((user, offered, session) ->
                USER.equals(user) && KeyUtils.compareKeys(allowed, offered));
    }

    /**
     * A key pair on disk, in the form OpenSSH and the plugin's client both read.
     * <p>
     * Generated by the client library the plugin ships, so the file the test
     * loads is the shape a tester's own key file is. An empty passphrase writes
     * an unencrypted key, which is a real state a tester can be in.
     *
     * @return the private key file; the public one is beside it, with .pub
     */
    Path generateKey(final String name, final String passphrase) throws Exception {
        final Path privateKey = directory.resolve(name);
        final com.jcraft.jsch.KeyPair pair =
                com.jcraft.jsch.KeyPair.genKeyPair(new com.jcraft.jsch.JSch(), com.jcraft.jsch.KeyPair.RSA, 2048);

        if (passphrase.isEmpty()) pair.writePrivateKey(privateKey.toString());
        else pair.writePrivateKey(privateKey.toString(), passphrase.getBytes(StandardCharsets.UTF_8));

        pair.writePublicKey(privateKey + ".pub", "testin");
        pair.dispose();

        return privateKey;
    }

    /**
     * The directory the server serves, so a test can put a file there without
     * the client and read one back the same way.
     */
    Path root() {
        return root;
    }

    /**
     * The server's host key as a {@code known_hosts} line for this port.
     * <p>
     * Given to the client so it can verify the host the way it will in front of
     * a tester. A test that switched host key checking off would be proving the
     * transport works in a configuration the plugin must never use.
     */
    String knownHostsLine() throws IOException, GeneralSecurityException {
        final KeyPair pair = server.getKeyPairProvider().loadKeys(null).iterator().next();

        return "[127.0.0.1]:" + port() + " " + PublicKeyEntry.toString(pair.getPublic()) + "\n";
    }

    @Override
    public void close() throws IOException {
        server.stop(true);

        if (!Files.exists(directory)) return;
        try (Stream<Path> paths = Files.walk(directory)) {
            paths.sorted(Comparator.reverseOrder()).forEach(path -> path.toFile().delete());
        }
    }
}
