package org.testin.sftp;

import org.testng.SkipException;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;
import static org.testng.Assert.expectThrows;

/**
 * Proving who this machine is, against a real server (#94).
 * <p>
 * Keys rather than passwords are how a team actually connects, and the two
 * states a tester's key can be in - encrypted and not - behave differently
 * enough to be worth separating. The wrong-key and wrong-passphrase cases are
 * here because "it connected" is only half the property; the other half is that
 * it does not connect when it should not.
 * <p>
 * The keys are generated by the client library the plugin ships, so the files
 * these tests load have the same shape as a tester's own.
 */
public class SftpAuthTest {

    private SftpTestServer server;
    private Path knownHosts;

    @BeforeMethod
    public void startServer() throws Exception {
        server = SftpTestServer.start();
        knownHosts = Files.createTempFile("testin-known-hosts", "");
        Files.writeString(knownHosts, server.knownHostsLine());
    }

    @AfterMethod
    public void stopServer() throws IOException {
        if (server != null) server.close();
        if (knownHosts != null) Files.deleteIfExists(knownHosts);
    }

    private SftpTransport connectWith(final SftpAuth auth) {
        return SftpTransport.open(new SftpAddress("127.0.0.1", server.port(), ""),
                SftpTestServer.USER, auth, knownHosts);
    }

    @Test
    public void anUnencryptedKeyConnects() throws Exception {
        final Path key = server.generateKey("plain_key", "");
        server.acceptOnly(Path.of(key + ".pub"));

        try (SftpTransport transport = connectWith(SftpAuth.withKey(key.toString(), ""))) {
            transport.write("case.json", "{}".getBytes(StandardCharsets.UTF_8));
            assertTrue(transport.exists("case.json"));
        }
    }

    /**
     * The case the plan cares about most: a key with a passphrase, which is what
     * a tester who followed any sensible instruction will have.
     */
    @Test
    public void anEncryptedKeyConnectsWithItsPassphrase() throws Exception {
        final Path key = server.generateKey("encrypted_key", "correct horse");
        server.acceptOnly(Path.of(key + ".pub"));

        try (SftpTransport transport = connectWith(SftpAuth.withKey(key.toString(), "correct horse"))) {
            transport.write("case.json", "{\"x\":1}".getBytes(StandardCharsets.UTF_8));
            assertEquals(transport.read("case.json"), "{\"x\":1}".getBytes(StandardCharsets.UTF_8));
        }
    }

    @Test
    public void theWrongPassphraseIsRefused() throws Exception {
        final Path key = server.generateKey("encrypted_key", "correct horse");
        server.acceptOnly(Path.of(key + ".pub"));

        final IllegalStateException refused = expectThrows(IllegalStateException.class,
                () -> connectWith(SftpAuth.withKey(key.toString(), "wrong")));

        assertTrue(refused.getMessage().contains("Could not connect"), refused.getMessage());
    }

    /**
     * A key the server was never told about does not get in, even though it is a
     * perfectly valid key and the passphrase is right.
     */
    @Test
    public void aKeyTheServerDoesNotKnowIsRefused() throws Exception {
        final Path allowed = server.generateKey("allowed_key", "");
        final Path other = server.generateKey("other_key", "");
        server.acceptOnly(Path.of(allowed + ".pub"));

        final IllegalStateException refused = expectThrows(IllegalStateException.class,
                () -> connectWith(SftpAuth.withKey(other.toString(), "")));

        assertTrue(refused.getMessage().contains("Could not connect"), refused.getMessage());
    }

    /**
     * The entry point the plugin actually calls, rather than the primitive
     * underneath it.
     * <p>
     * With no agent holding keys - the ordinary state of a fresh machine - it
     * must fall through to the key file and connect. Skipped when this machine
     * does have an agent with keys loaded, because then the correct behavior is
     * to use it, and this server has never heard of whatever it holds.
     */
    @Test
    public void withNoAgentItFallsThroughToTheKeyFile() throws Exception {
        if (SshAgent.loadedIdentities().isPresent()) {
            throw new SkipException("an agent on this machine is holding keys, which is the other path");
        }

        final Path key = server.generateKey("fallback_key", "a passphrase");
        server.acceptOnly(Path.of(key + ".pub"));

        try (SftpTransport transport = connectWith(SftpAuth.forKey(key.toString(), () -> "a passphrase"))) {
            transport.write("case.json", "{}".getBytes(StandardCharsets.UTF_8));
            assertTrue(transport.exists("case.json"));
        }
    }

    /**
     * And the passphrase is not fetched when it is not going to be used.
     * <p>
     * Reading it costs a keychain round trip, and on a machine with an agent it
     * would be asked for and thrown away.
     */
    @Test
    public void thePassphraseIsOnlyFetchedIfItIsNeeded() throws Exception {
        final boolean agentHasKeys = SshAgent.loadedIdentities().isPresent();
        final boolean[] asked = {false};

        SftpAuth.forKey("some-key", () -> {
            asked[0] = true;
            return "";
        });

        assertEquals(asked[0], !agentHasKeys,
                agentHasKeys ? "an agent is holding keys, so nothing should have been asked for"
                        : "no agent, so the key file's passphrase was needed");
    }

    /**
     * A machine that offers nothing is refused by the server, rather than by a
     * check here that would have to guess which of several things was missing.
     */
    @Test
    public void offeringNothingIsRefused() throws Exception {
        final Path key = server.generateKey("allowed_key", "");
        server.acceptOnly(Path.of(key + ".pub"));

        expectThrows(IllegalStateException.class, () -> connectWith(SftpAuth.NONE));
    }
}
